### ISSUE TITLE
`MP2_BNO_Bath` support for general fragments

### ISSUE THREAD

**Issue by obackhouse** [BoothGroup/Vayesta#7]
`MP2_BNO_Bath` currently seems to only support fragments from EWF rather than the abstract `Fragment` class. Example:

```
from pyscf import gto, scf
from vayesta.core import QEmbeddingMethod
from vayesta.core.bath import MP2_BNO_Bath

mol = gto.M(atom='O 0 0 0; O 0 0 1', basis='sto3g', verbose=0)

mf = scf.RHF(mol)
mf.kernel()

qemb = QEmbeddingMethod(mf)
qemb.iao_fragmentation()
frag = qemb.add_atomic_fragment([0])

bath = MP2_BNO_Bath(frag)
bath.kernel()
```

Which raises:

```
Traceback (most recent call last):
  File "bugs/b7.py", line 15, in <module>
    bath.kernel()
  File "/home/olli/git/vayesta/vayesta/core/bath/bno.py", line 35, in kernel
    self.c_bno_occ, self.n_bno_occ = self.make_bno_bath('occ')
  File "/home/olli/git/vayesta/vayesta/core/bath/bno.py", line 55, in make_bno_bath
    c_bno, n_bno = self.make_bno_coeff(kind)
  File "/home/olli/git/vayesta/vayesta/core/bath/bno.py", line 232, in make_bno_coeff
    e_mp2_full *= self.fragment.get_energy_prefactor()
AttributeError: 'Fragment' object has no attribute 'get_energy_prefactor'
```

**Comment by Majokux** [comment]
The code has obviusly changed quite a bit in the meantime, but the following now runs for an abstract base class fragment:

```
from pyscf import gto, scf
from vayesta.core.qemb import Embedding
from vayesta.core.bath import DMET_Bath
from vayesta.core.bath.bno import MP2_BNO_Bath

mol = gto.M(atom='O 0 0 0; O 0 0 1', basis='sto3g', verbose=0)

mf = scf.RHF(mol)
mf.kernel()

emb = Embedding(mf)
with emb.iao_fragmentation() as frag:
    f = frag.add_atomic_fragment(0)

dmet = DMET_Bath(f)
dmet.kernel()
bath = MP2_BNO_Bath(f, dmet, 'occupied')
bath.kernel()
```

Can we thus close this?

**Comment by obackhouse** [comment]
Sorry - missed this message, closed
